### ISSUE TITLE
Unable to locate metasploit in Kali

### ISSUE THREAD

**Issue by psychomad** [peterpt/pipe_finder#1]
Hi
I installed the app and was unable to locate the metapsloit-framework folder, im using kali.
I modified the function LOCATE with 
/opt/metasploit-framework/embedded/framework/modules/
and it work.
Im not a coder so i don't know how to write a code specific for kali but i think add this path for kali users will be fine (maybe a ELSE cmd?)
Just to let you know

**Comment by peterpt** [comment]
thanks for the tip , i did not knew that some metasploit installations had that directory structure .
I will make some changes in code to look for that specific directory structure in case the main is not detected . Was your metasploit installation made by "apt-get"?
However , after i change the code you should clone this git again , or you will not be able to update your script every time i add changes to the code or implement options , the reason is that when you write "git pull" , git will drop you an arror on updating your script because it is different from the main script here .

**Comment by peterpt** [comment]
I changed the script to look also for that directory structure .
Can you clone again the git and test it on your linux , just to make sure now it works ok ?

Thank you

**Comment by psychomad** [comment]
Hi,
No metasploit in Kali coming pre installed in such way, in fact there's a problem also with gems. Tonight i will clone and i will let you know. Cya

**Comment by psychomad** [comment]
Just try and work fine! thank a lot

**Comment by peterpt** [comment]
ok
